### ISSUE TITLE
[BUG] possible issue with DIDDelegateChanged Event on Hardhat

### ISSUE THREAD

**Issue by jvlkl** [decentralized-identity/ethr-did-resolver#143]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Current Behavior
Unfortunately I am not able to share some code so let me try to explain my problem. Please correct me if the behaviour below is actually intended or I got sth. wrong. 

I have a contract calling the functions addDelegate and revokeDelegate from a EIP-1056 DID registry. My aim is to update the delegate of a DIDDocument with a new delegate. To achieve this I am first calling addDelegate which leads to the following state:

delegate-1: old delegate/address
delegate-2: new delegate/address

Then, after calling revoke Delegate for delegate-1 I will end up with this state: 

delegate-1 removed
delegate-2 new delegate/address
delegate-3 old delegate/address

### Expected Behavior

as for my understanding delegate-3 should not be included after revoking its delegation, there should just be a "gap" for the DIDDelegateChanged Event when adding the next delegate e.g.:

delegate-1 removed
delegate-2 new delegate
delegate-3 old delegate (should not be showing up in the Document)
delegate-4 possible new delegate

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Setup local hardhat network
2. Deploy EthrDIDRegistry
3. add a delegate and then revoke the old one

#### Environment Details

- local Hardhat network

#### Alternatives you considered

tried to mine new blocks between calling addDelegate and revokeDelegate to be 100% sure that the delegate is removed in the new block.

**Comment by mirceanis** [comment]
Thank you for posting!

Did mining blocks between operations change the behavior?

Do you get the same issue using ganache?

Your scenario sounds perfect as a test. Are you willing to contribute such a test?

I'm not sure if hardhat can be mixed with ganache, but if it can't I would also be ok with replacing it entirely
