### ISSUE TITLE
[proposal] Add Secp256r1 as possible key type

### ISSUE THREAD

**Issue by jrhender** [decentralized-identity/ethr-did-resolver#144]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Currently one can use the following key types: `Secp256k1|Rsa|Ed25519` when using `setAttribute`. I would like to also be able to set `Secp256r1`. I believe that would mean that `did:ethr` resolvers would then need to be updated to resolve this attribute data correctly.

**Describe alternatives you've considered**
Our objective is to allow an IoT device, with has a `secp256r1` to be able to authenticate as an `ethr` DID. I think that because we cannot currently add the `secp256r1` public key to the device's DID document, one would need to either:
- Use a different IoT device which has access to different cryptographic signatures
- Use a different did method which supports this key type
- Fork this resolver 

**Additional context**

**Comment by jrhender** [comment]
Hi @mirceanis . EnergyWeb doesn't need this feature at the moment, so this issue could be closed if you would like. I think knowing that it would be possible and that you would consider a PR that implements this is enough for now from EnergyWeb's perspective. When we migrate to using this resolver for our `ethr` DIDs, we'll probably open a PR for this if it hasn't been done already.

**Comment by mirceanis** [comment]
@jrhender Thanks for letting me know.
I'll leave it open for now since this relates to how we would deal with other algorithms too, and if planets align, maybe someone even contributes a PR to address this before we have bandwidth to get to it :)
