### ISSUE TITLE
[BUG] the LD context is outdated and not really usable

### ISSUE THREAD

**Issue by mirceanis** [decentralized-identity/ethr-did-resolver#151]
The @context included in the response is outdated (https://identity.foundation/EcdsaSecp256k1RecoverySignature2020/lds-ecdsa-secp256k1-recovery2020-0.0.jsonld).
It has to be updated to `https://w3id.org/security/suites/secp256k1recovery-2020/v2`

**Comment by About7Sharks** [comment]
#154
