### ISSUE TITLE
[BUG] blockchainAccountId format is outdated

### ISSUE THREAD

**Issue by mirceanis** [decentralized-identity/ethr-did-resolver#152]
The [CAIP10](https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-10.md) format has been updated for ethereum from `<address>@eip155:<chainId>` to `eip155:<chainId>:<address>`

The DID document result must be updated to use the latest variant.

See:
https://github.com/decentralized-identity/ethr-did-resolver/blob/2a66a2bfc29ebb59a33967f6dec8cdc676c2fee5/src/resolver.ts#L177
https://github.com/decentralized-identity/ethr-did-resolver/blob/2a66a2bfc29ebb59a33967f6dec8cdc676c2fee5/src/resolver.ts#L267

**Comment by About7Sharks** [comment]
https://github.com/decentralized-identity/ethr-did-resolver/pull/153
