### ISSUE TITLE
[BUG] ESM import

### ISSUE THREAD

**Issue by RobertoSnap** [decentralized-identity/ethr-did-resolver#171]
### Prerequisites

**Version**:  "ethr-did-resolver": "7.0.0-alpha.2"

### Current Behavior

Trying to import getResolver from ethr-did-resolver in an ESM project fails with message:

`SyntaxError: The requested module 'ethr-did-resolver' does not provide an export named 'getResolver'`

### Expected Behavior

I should be able to import getResolver without error messages. 

### Failure Information

Could be something local. Useing Ava test suite.
Everything looks good, its exported. Types are working, i can navigate to the function. I see resolver.js.

Could it be 
![CleanShot 2022-10-17 at 09 16 18](https://user-images.githubusercontent.com/4772930/196112645-47161e03-945b-4f33-88ca-80828b2b00b8.png)

#### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. clone https://github.com/symfoni/vc-box, pnpm i , pnpm test

#### Environment Details

* node/browser version: v18.8.
* OS Version:Mac
* Device details:

#### Failure Logs/Screenshots

![CleanShot 2022-10-17 at 09 18 47](https://user-images.githubusercontent.com/4772930/196113035-fdb449ac-8b0d-499b-a868-26fde2cf636f.png)

**Comment by RobertoSnap** [comment]
If i do a dynamic import:

https://github.com/symfoni/vc-box/blob/main/src/vc-box.ts#L153

I get this:
```  /Users/robin/code/vc-box/node_modules/.pnpm/ethr-did-resolver@7.0.0-alpha.2/node_modules/ethr-did-resolver/lib/index.js:1
  import { getResolver } from './resolver';
  ^^^^^^

  SyntaxError: Cannot use import statement outside a module````

**Comment by RobertoSnap** [comment]
That last one seems to point to package.json is not module, but i guess there are some reason one must go for a hybrid approach: https://stackoverflow.com/questions/58384179/syntaxerror-cannot-use-import-statement-outside-a-module

**Comment by RobertoSnap** [comment]
haha, working in version: [7.0.0-alpha.3](https://www.npmjs.com/package/ethr-did-resolver/v/7.0.0-alpha.3) which i saw was released: @mirceanis :)

**Comment by RobertoSnap** [comment]
Can i get a heads up when https://www.npmjs.com/package/did-resolver also has this ESM changes?

**Comment by mirceanis** [comment]
Of course.
I think today or the next couple days

**Comment by mirceanis** [comment]
@RobertoSnap please see decentralized-identity/did-resolver#139

Please add your review there too 🙏

**Comment by RobertoSnap** [comment]
Sorry, was sick for some days. Back now, thank you ☺️
