### ISSUE TITLE
[BUG] using ethr-did-resolver ESM results in import failure

### ISSUE THREAD

**Issue by mirceanis** [decentralized-identity/ethr-did-resolver#175]
### Current Behavior

When using `ethr-did-resolver@7.0.1`  in an ESM setting, named imports don't work:

```ts
import { getResolver as ethrDidResolver } from 'ethr-did-resolver'
```

throws this error:
```
export 'getResolver' (imported as 'ethrDidResolver') was not found in 'ethr-did-resolver' (possible exports: default)
```

### Expected Behavior

Named imports should work.

#### Environment Details

ethr-did-resolver@7.0.1
react@18

### Workarounds

```ts
import * as ETHR from 'ethr-did-resolver'
const ethrDidResolver = ETHR.getResolver
```

**Comment by moisesja** [comment]
Create a simple vue.js with vite and the error is still persisting. this occurs inside the esm/index.js file
![Screenshot 2024-12-10 at 9 07 44 AM](https://github.com/user-attachments/assets/fe212042-22ea-4fe8-a99f-523a4a220847)
The dependent import cjsModule cannot be located in the expected ..lib/index.js file (file is not part of the compilation)
