### ISSUE TITLE
[BUG] Resolver adds more keys than it should

### ISSUE THREAD

**Issue by ismapolis** [decentralized-identity/ethr-did-resolver#184]
### Current Behavior

When i send a setAttribute transaction with key equals "did/pub/Secp256k1/enc/<encoding>" then on the did document it adds an entry on assertionMethod and KeyAgreement. When i select veriKey instead of enc it works fine.

### Expected Behavior

The resolver should just adds an entry on KeyAgreement.

### Failure Information

Please help provide information about the failure.

#### Steps to Reproduce

I am using a react app for testing with some select elements for key purpose and encoding. For the blockchain I am using Ganache and Metamask as Web3 provider. 
Here is a fragment of the code I use for emitting the transaction. "keyuse" and "encode" are the values from the select elements.

``` javascript
let key = "did/pub/Secp256k1/" + keyuse + "/" + encode;
console.log(key);
await contract.methods
      .setAttribute(
        accounts[0],
        stringToBytes32(key),
        "0x" + publicKey,
        31536000
      )
      .send({ from: accounts[0] });
```

#### Environment Details

I attach the react component code on zip.

[index.zip](https://github.com/decentralized-identity/ethr-did-resolver/files/11286649/index.zip)

#### Failure Logs/Screenshots

DID initial doc
![imagen](https://user-images.githubusercontent.com/53060433/233378111-80bb904c-e4a9-412c-b578-15a7a6cb9147.png)

After I emit a transaction with enc value

![imagen](https://user-images.githubusercontent.com/53060433/233378761-66ce6ee0-7c91-478a-8801-f898bb587336.png)

And then when I try to revoke that verificationMethod

![imagen](https://user-images.githubusercontent.com/53060433/233379522-cedc9494-7f6f-4c16-b73e-ca000623bb18.png)

**Comment by ismapolis** [comment]
> Sounds like a bug.. it should not be added to assertionMethod; just to keyAgreement.

Hello I have been reviewing the code and it is not a bug, it is coded like that but I dont know why, maybe an older version of did:ethr specification?
Here it filters "sigAuth" and "enc" and adds the key to the corresponding section, but not for assertion.
![image](https://user-images.githubusercontent.com/53060433/235308497-52ef768b-40f2-460e-b8b9-7dd2b640ece9.png)

Later all the verification methods are added to assertionMethod don't know why.
![image](https://user-images.githubusercontent.com/53060433/235308615-7be40821-a0c6-40c5-8d6d-517b81b6c289.png)

I even checked the tests and in the case of adding an "enc" key the test checks that it is added to KeyAgreement and assertionMethod.
![image](https://user-images.githubusercontent.com/53060433/235308839-12310d14-1c6a-45b0-80db-6c42268a45a7.png)

I could fix it and make a PR If you approve it.

**Comment by mirceanis** [comment]
> > Sounds like a bug.. it should not be added to assertionMethod; just to keyAgreement.
> 
> Hello I have been reviewing the code and it is not a bug, it is coded like that but I dont know why, maybe an older version of did:ethr specification? Here it filters "sigAuth" and "enc" and adds the key to the corresponding section, but not for assertion. ![image](https://user-images.githubusercontent.com/53060433/235308497-52ef768b-40f2-460e-b8b9-7dd2b640ece9.png)
> 
> Later all the verification methods are added to assertionMethod don't know why. ![image](https://user-images.githubusercontent.com/53060433/235308615-7be40821-a0c6-40c5-8d6d-517b81b6c289.png)
> 
> I even checked the tests and in the case of adding an "enc" key the test checks that it is added to KeyAgreement and assertionMethod. ![image](https://user-images.githubusercontent.com/53060433/235308839-12310d14-1c6a-45b0-80db-6c42268a45a7.png)
> 
> I could fix it and make a PR If you approve it.

It's still a bug, even if it looks intentional.
The origin of the bug is from the early days of the DID spec, when keys didn't need to have a clear verification relationship. It's also common for authentication keys to also be usable as assertion keys, but it's debatable whether that should be the case with keyAgreement.

Generally, this DID method leans toward fewer transactions where possible, which is why all keys are automatically dumped in the assertion method relationship.

Fixing this would be a breaking change, however, and should also include an update to the spec.

**Comment by ismapolis** [comment]
Hello I would like to confirm this with you. The current spec states in [key purposes](https://github.com/decentralized-identity/ethr-did-resolver/blob/master/doc/did-method-spec.md#key-purposes) that every key is added to its corresponding section not in more than one. The change I proposed wouldn't breaking. It would just update the code to the referenced spec.
