### ISSUE TITLE
This lib should also expose the resolve function

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/ethr-did-resolver#23]
This lib only exposes the `registerMethod` function to register the `resolve: did => didDocument` function to [did-resolver](https://github.com/uport-project/did-resolver/)

I suggest it also exposes the `resolve` function on its own, so that people can use it independently from `did-resolver`

**Comment by Iamshashvat** [comment]
Same Issue!
How can we access resolve function it's not exposed?

**Comment by vasa-develop** [comment]
@gjgd @Iamshashvat [**here is a demo**](https://github.com/cluster-labs/did-ethr-demo) showing how to resolve the DID document

**Comment by mirceanis** [comment]
Is this still an issue?
If so, please reopen.
