### ISSUE TITLE
TypeError when running example from readme

### ISSUE THREAD

**Issue by jordanmmck** [decentralized-identity/ethr-did-resolver#39]
I'm getting `Uncaught TypeError: ethr_did_resolver__WEBPACK_IMPORTED_MODULE_1___default(...) is not a function` when trying to run the code given at the bottom of the readme. Here is the exact code:

```
import { Resolver } from 'did-resolver';
import getResolver from 'ethr-did-resolver';

const registryAddress = '0xdca7ef03e98e0dc2b855be647c39abe984fcf21b';
const providerConfig = { rpcUrl: 'https://rinkeby.infura.io/ethr-did', registry: registryAddress };

const ethrDidResolver = getResolver(providerConfig);
const didResolver = Resolver(ethrDidResolver);
```

Not sure if it matters, but I made a clean `create-react-app` project to run this code in.

**Comment by aldigjo** [comment]
@jordanmmck try importing getResolver as a named import by putting curly brackets around it `import { getResolver} from 'ethr-did-resolver'` we probably need to update the readme

**Comment by jordanmmck** [comment]
Thanks @aldigjo, importing as you've shown above results in `getResolver` being undefined.

**Comment by aldigjo** [comment]
@jordanmmck are you on ethr-did-resolver version 1.0.2?

**Comment by jordanmmck** [comment]
Yes

**Comment by mirceanis** [comment]
> Not sure if it matters, but I made a clean `create-react-app` project to run this code in.

It does matter that it's a react app. There's a conflict between the files produced during build and the react context. It seems that it's picking up the wrong file (`ethr-did-resolver.ejs` instead of `*.js`) when importing it in a frontend app.
