### ISSUE TITLE
Documentation shows incorrect import for latest version

### ISSUE THREAD

**Issue by justinmchase** [decentralized-identity/ethr-did-resolver#60]
All of the examples I'm finding have a snippet such as:
```ts
import getResolver from 'ethr-did-resolver'
```

But then looking in the code here:
https://github.com/decentralized-identity/ethr-did-resolver/blob/develop/src/ethr-did-resolver.js#L298

It should be:
```ts
import { getResolver } from 'ethr-did-resolver'
```

**Comment by mirceanis** [comment]
@justinmchase Thank you for reporting this.
I fixed the snippet that appeared in the readme.
Can you point to other places that show the wrong import statement?

**Comment by justinmchase** [comment]
It looks like you covered it all in the other PR https://github.com/uport-project/uport-credentials/pull/197
