### ISSUE TITLE
Change 'owner' to 'controller' to follow W3C Spec

### ISSUE THREAD

**Issue by pensivej** [decentralized-identity/ethr-did-resolver#75]
**Is your feature request related to a problem? Please describe.**
As I have also proposed in `did-resolver` repo (https://github.com/decentralized-identity/did-resolver/pull/55),
to comply with the latest W3C DID spec, the `publicKey` property MUST have `id`, `type`, and `controller` properties.
`owner` is a legacy that needs to be changed.

**Describe the solution you'd like**
change the `owner` to `controller`

**Describe alternatives you've considered**
N/A

**Additional context**
I will propose this change to other repos (e.g. did-resolver, did-registrar, etc.)

**Comment by mirceanis** [comment]
This is fixed by #81
If the breaking change is causing issues that have no other solution, please reopen this issue to discuss a workaround.
