### ISSUE TITLE
[proposal] add/specify 'alsoKnownAs' property for ethr-did

### ISSUE THREAD

**Issue by nikolockenvitz** [decentralized-identity/ethr-did-resolver#94]
As already mentioned in uport-project/daf#260 the DID spec includes the `alsoKnownAs` property and should be specified and added for ethr-did. Before opening a PR directly, I wanted to propose my ideas here and get some feedback.

**update**
I would think the easiest is to use the `setAttribute`/`revokeAttribute` method of the ethr did registry smart contract. For the attribute name I would think of `did/aka` or `did/alsoKnownAs`. Actually I would prefer the latter one because it's more explicit and length doesn't matter as it is padded to 32 bytes anyway. In contrast to public keys and services, the attribute name is completly static and doesn't include any other information, so it's no problem to have a long name. The attribute value could just be the hex-encoded identifier/URI that should be added to the `alsoKnownAs` property.

Options:
* `did/aka`
* `did/alsoKnownAs` (&larr; my suggestion)
* ...

**resolve**
When resolving the DID document, an array of all these values (that didn't expired yet or have been revoked afterwards) should be returned. One question to be answered is, whether `alsoKnownAs` should be an empty array or whether this property shouldn't be included in the DID document at all if there are no values. It suggest to do it similar to the others (public key, service, ...) and include the `alsoKnownAs` property only if the array is not empty.

Options:
* `{ id: "...", alsoKnownAs: [] }`
* `{ id: "..." }` (&larr; my suggestion)
* ...

Your opinion on that / feedback / any other ideas?

Checklist for next steps:
- [ ] update ethr did spec
- [ ] write tests
- [ ] update `wrapDidDocument()` method of ethr-did-resolver

**Comment by nikolockenvitz** [comment]
I implemented my proposed changes (see linked pull request). Feedback is welcome.

**Comment by rado0x54** [comment]
Updated link to spec: https://w3c.github.io/did-core/#also-known-as
Feature is currently at risk.
